// Generated by CoffeeScript 1.3.1
(function() {

  app.models.UpdateHandler = (function() {

    UpdateHandler.name = 'UpdateHandler';

    function UpdateHandler() {}

    UpdateHandler.prototype.handleUpdate = function(data) {
      if (this[data.change]) {
        return this[data.change](data);
      }
    };

    UpdateHandler.prototype.post = function(data) {
      var modelData;
      console.log("POST");
      modelData = _.extend({}, data.req, data.resp);
      console.log(modelData);
      if (data.url === "/data/DayAtHome") {
        return window.model.add_unique(modelData);
      }
    };

    UpdateHandler.prototype["delete"] = function(data) {
      return console.log("DELETE");
    };

    return UpdateHandler;

  })();

}).call(this);
