// Generated by CoffeeScript 1.3.1
(function() {

  app.models.UpdateHandler = (function() {

    UpdateHandler.name = 'UpdateHandler';

    function UpdateHandler() {}

    UpdateHandler.prototype.handleUpdate = function(data) {
      if (this[data.change]) {
        return this[data.change](data);
      }
    };

    UpdateHandler.prototype.post = function(data) {
      var modelData;
      modelData = _.extend({}, data.req, data.resp);
      if (data.url === "/data/DayAtHome") {
        return window.model.add_unique(modelData);
      }
    };

    UpdateHandler.prototype["delete"] = function(data) {
      var id, item;
      id = (data.url.split('/')).pop();
      item = window.model.get(id);
      if (item) {
        return window.model.remove(item);
      }
    };

    return UpdateHandler;

  })();

}).call(this);
