// Generated by CoffeeScript 1.3.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  app.models.User = (function(_super) {

    __extends(User, _super);

    User.name = 'User';

    function User() {
      this.login = __bind(this.login, this);

      this.create = __bind(this.create, this);
      return User.__super__.constructor.apply(this, arguments);
    }

    User.prototype.create = function(username, password, options) {
      options = options != null ? options : {};
      options.url = "/users";
      return this.save({
        username: username,
        password: password
      }, options);
    };

    User.prototype.login = function(username, password, options) {
      options = options != null ? options : {};
      options.data = {
        username: username,
        password: password
      };
      options.url = "/login";
      return this.fetch(options);
    };

    return User;

  })(Backbone.ParseModel);

}).call(this);
